version: "3.9"
   
services:
  db:
    image: postgres:16.3
    environment:
      - POSTGRES_DB=warehouse
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=rHya2Lm4fT
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/warehouse
    ports:
      - "8000:8000"
    depends_on:
      - db
