# Generated by Django 5.0.7 on 2024-07-27 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sparepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('units', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('replaceable_with', models.ManyToManyField(blank=True, to='spareparts.sparepart')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedSparepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_amount', models.PositiveIntegerField()),
                ('current_amount', models.PositiveIntegerField(blank=True, default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.task')),
                ('sparepart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='spareparts.sparepart')),
            ],
        ),
        migrations.CreateModel(
            name='SparepartBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('warehouse', models.CharField(max_length=128)),
                ('sparepart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='spareparts.sparepart')),
            ],
        ),
    ]
